FROM docker.io/library/ubuntu:latest AS base

USER root

WORKDIR /root

# Update the repos and add the 32-bits architecture.
ARG DEBIAN_FRONTEND=noninteractive
RUN dpkg --add-architecture i386 \
    && apt-get update -y \
    && apt-get install -y --no-install-recommends ca-certificates libc6:i386 libcrypt1:i386 libgcc-s1:i386 libstdc++6:i386 wine bash tar wget gcc-multilib:i386 \
    && rm -rf /var/lib/apt/lists/*

ENV STEAMCMD_PATH=/gameserver/steamcmd
ENV STEAMCMD_LOGIN=anonymous
ENV GS_APPID=2271150
ENV GS_PATH=/gameserver/loya

RUN userdel ubuntu \
 && useradd \
 -ms /sbin/nologin \
 -d /gameserver \
 gameserver

USER gameserver

RUN mkdir -p ${STEAMCMD_PATH} ${GS_PATH}

WORKDIR /gameserver/

RUN wget -qO- "https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz" \
 | tar -C /gameserver/steamcmd -zxvf - \
 && ${STEAMCMD_PATH}/steamcmd.sh +quit

COPY ./data/loya.sh /gameserver/loya.sh

COPY ./data/steam_updater.sh /gameserver/steam_updater.sh

ENTRYPOINT ["/bin/bash", "/gameserver/loya.sh"]

VOLUME ${GS_PATH}

EXPOSE 15010
